version: "3"

volumes:
  local_mongodb_data: {}
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - /home/ubuntu/config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  mongodb:
    restart: always
    image: mongo
    container_name: "docker-mongodb"
    volumes:
      - local_mongodb_data:/data/db
    env_file:
      - ./.envs/.mongodb
    ports:
      - "27017:27017"

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_DEBUG=False
    build: ./
    command: >
      bash -c "./manage.py migrate &&
                gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - mongodb

  documentation:
    restart: always
    build: ./
    command: "mkdocs serve "
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
