# Generated by Django 3.2.8 on 2021-11-01 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='Comment', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created time', verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated time', null=True)),
                ('parent', models.ForeignKey(help_text='Check_parent_comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comments.comments')),
                ('post', models.ForeignKey(help_text='Post', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
