# Generated by Django 3.2.9 on 2021-11-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Check_parent_comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comments.comment'),
        ),
    ]
