# Generated by Django 3.2.9 on 2021-11-03 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercount',
            name='user',
            field=models.ForeignKey(help_text='게시글 본 유저', on_delete=django.db.models.deletion.CASCADE, related_name='user_count', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', help_text='카테고리', on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='usercount',
            field=models.ManyToManyField(through='posts.UserCount', to=settings.AUTH_USER_MODEL),
        ),
    ]
